api_platform:
    title: Systemeio API
    version: 0.0.1
    formats:
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
    docs_formats:
        html: [ 'text/html' ]
    enable_re_doc: false
    graphql:
        graphiql:
            enabled: false
        graphql_playground:
            enabled: false
    exception_to_status:
        Doctrine\ORM\EntityNotFoundException: 400
        ApiPlatform\Validator\Exception\ValidationException: 400
        Exception: 400